### ISSUE TITLE
No comments in the code

### ISSUE THREAD

**Issue by salaki** [ZigaSajovic/dCpp#4]
Could you please add comments inside the code to explain how to construct the differentiable virtual memory?

**Comment by ZigaSajovic** [comment]
Dear @salaki 
the code contains no comments, as the process of implementing (this library for) automatic differentiation through the theory of [Operational calculus on programming spaces](https://arxiv.org/abs/1610.07690) is explained in the manuscript [Implementing Operational calculus on programming spaces](https://arxiv.org/abs/1612.02731). The mentioned manuscript contains all the pivotal sections of the source code, equipped with the needed explanations and derivations. Perhaps this post on [Deep Learning and Virtual Tensor Machines](https://zigasajovic.github.io/Deep-Learning-and-Virtual-Tensor-Machines) may be of further assistance in understanding the subject.

Please know, that if you have any specific questions regarding the understanding the contents of the attached papers or the source code, you are invited to contact me.
