### ISSUE TITLE
Is dCpp thread safe?

### ISSUE THREAD

**Issue by manuelreis** [ZigaSajovic/dCpp#5]
Hi,

what would be the implications if one runs dCpp in a multithreaded environment?

**Comment by ZigaSajovic** [comment]
dCpp is as thread safe as the [shared pointer](https://en.cppreference.com/w/cpp/memory/shared_ptr) its implementation employs. To learn more about, you can read [this](https://stackoverflow.com/questions/9127816/stdshared-ptr-thread-safety-explained) stackoverflow thread.
