### ISSUE TITLE
Could I evaluate derivatives at different point?

### ISSUE THREAD

**Issue by miaodi** [ZigaSajovic/dCpp#7]
Could I revise the value in var so that I can evaluate equation at different points?

**Comment by ZigaSajovic** [comment]
Derivatives can be evaluated at any point, if a function is created. Than simply call the function with different inputs.

```c++
var foo(var &x0, ..., var& xn){
    //insert your code here
   return ...
}
d_a = foo(a0, .., an).d(&x0) //derivative at one point
d_b=foo(b0, .., bn).d(&x0) // derivative at a different point
```
This is equivalent to stating

> d_a = dfoo/dx0 (a0, ..., an)  
d_b = dfoo/dx0 (b0, ..., bn) 

Note the subtle difference. You do not revise the values of var. You re-evaluate the function at the appropriate points. If needed, you can reassign their values inside the body of the function. This is the difference between symbolic and automatic differentiation.

I hope this clears any confusion. If not, please provide [a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve), a short program, commented with your thoughts and questions at appropriate places.

**Comment by ZigaSajovic** [comment]
Dear @miaodi,

given the lack of a response, I will assume the issue has been resolved. In light of this, I am closing it. If it has not been resolved, consider reopening the issue.
